### ISSUE TITLE
Incorrect reference to C procedure

### ISSUE THREAD

**Issue by sebastian-mutz** [interkosmos/fortran-sdl2#11]
Hi Philipp,

In **sdl2_image.f90, line 27**, you specify the c procedure binding label _IMG_LoadTexture_
> function img_load(file_name) bind(c, name='IMG_LoadTexture')

If I'm not mistaken the correct c procedure binding should be _IMG_Load_?

Great work btw. I enjoy playing around with it.

Best wishes
Sebastian

**Comment by interkosmos** [comment]
Thank you for pointing this out. Has been fixed with commit 31d6884c700564989993282f8e404cb4f9d3c25f.
