### ISSUE TITLE
All is broken now

### ISSUE THREAD

**Issue by angelog0** [interkosmos/fortran-sdl2#12]
I do not understand why when you change your code you do it in a very not backward compatible way.

Now  a lot of my applications do not build any more just because you  wanted be more elegant adding `kind=c_char...` which in some cases increases the length of the line and you thought to fix it adding the option `-ffree-line-length-none`. Would it be better to break the line? For example, here this works without that **annoying** option:

```
-    character(kind=c_char, len=*), parameter :: SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN  = 'SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN'
+    character(kind=c_char, len=*), parameter :: SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN  = &
+         'SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN'
```

In a module I have

```
use sdl2, only: SDL_INIT_VIDEO, SDL_RENDERER_SOFTWARE, SDL_WINDOW_SHOWN, &
       SDL_WINDOWPOS_UNDEFINED, &
       SDL_QUITEVENT, SDL_KEYDOWN, SDLK_ESCAPE, SDLK_q, &
       SDL_KEYDOWN, SDL_MOUSEBUTTONDOWN, SDL_MOUSEWHEEL, &
       SDL_WINDOWEVENT, SDL_WINDOWEVENT_CLOSE, SDL_WINDOWEVENT_EXPOSED, &
       SDL_WINDOWEVENT_SHOWN, &
       sdl_event, sdl_point, sdl_rect, &
       sdl_create_renderer, sdl_create_window, &
       sdl_destroy_renderer, sdl_destroy_window, &
       sdl_get_error, sdl_get_mouse_state, &
       sdl_init, sdl_poll_event, sdl_quit, &
       sdl_render_clear, sdl_render_draw_line, sdl_render_draw_lines, &
       sdl_render_draw_point, sdl_render_draw_points, sdl_render_draw_rect, &
       sdl_render_draw_rects, sdl_render_fill_rect, sdl_render_fill_rects, &
       sdl_render_get_viewport, sdl_render_present, &
       sdl_render_set_viewport, sdl_set_render_draw_color
```

and never pass column 79... (my Emacs is configured to work with 80 columns and 50 rows).

Often you waste a lot of blanks just because you want all the `=` (and so on), aligned... really do you think that the resulting code is more readable?

And why renaming the repo `f03sdl2` to `f08sdl2`? Now I should change all the scripts/Makefiles to build the apps.. Why not using names like `fortran_sdl2`, `fsdl2` so that they will remain fixed even with other Fortran standard? 

Last but not least, the file `sdl2.f90` is so big that Emacs has difficulties to handle it... Wouldn't have been better to break it in more file (even _logically_)?

No, I can't upgrade my local repo to your change. It would take too long to fix things here and I have no time.

**Comment by interkosmos** [comment]
> I do not understand why when you change your code you do it in a very not backward compatible way.

Sorry to hear that. But the Fortran SDL 2.0 interface is still in development, so API breaks may occur.

> Would it be better to break the line?

I will change to line-breaks to avoid `-ffree-line-length-none`.

> Often you waste a lot of blanks just because you want all the `=` (and so on), aligned... really do you think that the resulting code is more readable?

Actually, I do. But as I wrote, I’ll change back to line-breaks.

> And why renaming the repo `f03sdl2` to `f08sdl2`?

The interfaces to `SDL_Thread` made it necessary to change to Fortran 2008 standard. Please excuse the hassle.

> Last but not least, the file `sdl2.f90` is so big that Emacs has difficulties to handle it... Wouldn't have been better to break it in more file (even logically)?

You are right. I consider moving to Fortran submodules in future.

**Comment by angelog0** [comment]
Even if you need to use F2008, why do you need to reflect that in the name of the repo?

Anyway, thanks for this work.

**Comment by angelog0** [comment]
After your last changes, it seems that I can rebuilt all my apps just applying this patch:

```
--- SDL2_app.f90~       2019-07-22 16:03:35.753893600 +0200
+++ SDL2_app.f90        2019-11-03 22:37:24.472436500 +0100
@@ -2,7 +2,7 @@
 ! Author: ANGELO GRAZIOSI
 !
 !   created   : Sep 08, 2018
-!   last edit : Jul 22, 2019
+!   last edit : Nov 03, 2019
 !
 !   Module to create SDL2 Fortran applications in DC or WC
 !
@@ -43,7 +43,8 @@
        sdl_render_draw_point, sdl_render_draw_points, sdl_render_draw_rect, &
        sdl_render_draw_rects, sdl_render_fill_rect, sdl_render_fill_rects, &
        sdl_render_get_viewport, sdl_render_present, &
-       sdl_render_set_viewport, sdl_set_render_draw_color
+       sdl_render_set_viewport, sdl_set_render_draw_color, &
+       uint8

   implicit none
   private
@@ -398,8 +399,8 @@
        a = 255
     end if

-    rc = sdl_set_render_draw_color(renderer,int(r,2),int(g,2),int(b,2), &
-         int(a,2))
+    rc = sdl_set_render_draw_color(renderer,uint8(r),uint8(g),uint8(b), &
+         uint8(a))
   end subroutine set_rgba_color

   subroutine get_viewport(rect)
@@ -422,8 +423,8 @@
     !
     ! Just use the LOW LEVEL routine:
     !
-    rc = sdl_set_render_draw_color(renderer,int(0,2),int(0,2),int(0,2), &
-         int(255,2))
+    rc = sdl_set_render_draw_color(renderer,uint8(0),uint8(0),uint8(0), &
+         uint8(255))
     rc = sdl_render_clear(renderer)
   end subroutine clear_screen

@@ -436,8 +437,8 @@
     rect%x = 0
     rect%y = 0

-    rc = sdl_set_render_draw_color(renderer,int(0,2),int(0,2),int(0,2), &
-         int(255,2))
+    rc = sdl_set_render_draw_color(renderer,uint8(0),uint8(0),uint8(0), &
+         uint8(255))
     rc = sdl_render_fill_rect(renderer,rect)
   end subroutine clear_viewport
```

Thanks a lot!

**Comment by interkosmos** [comment]
> Even if you need to use F2008, why do you need to reflect that in the name of the repo?

Retrospectivly, it may not be the best idea. Perhaps, I’ll stay away from this naming scheme in future.
