### ISSUE TITLE
catching when sdl_surface (or other types) not defined

### ISSUE THREAD

**Issue by freevryheid** [interkosmos/fortran-sdl2#20]
Using this:

image => sdl_load_bmp('card.bmp' // c_null_char)

If the file is not found, sdl_load_bmp returns without defining sdl_surface. Subsequent calls using this undefined sdl_surface will work even though the sdl_surface is invalid. One way to catch this:   

rc = image%w  ! this will fail with invalid memory reference if the image was .not. loaded

I'm not sure how to address this issue as we have no exceptions in Fortran. I'm thinking maybe having a:

if (.not. associated(ptr)) ...

defined in the sdl2 calling function instead of just returning as in:

ptr = sdl_load_bmp_rw(sdl_rw_from_file(file, 'rb' // c_null_char), 1)
if (.not. c_associated(ptr))  then !return
  error stop "file not found"

**Comment by interkosmos** [comment]
The function `sdl_load_bmp()` should return `null()` is [the file could not be loaded](https://github.com/interkosmos/fortran-sdl2/blob/0a41c447353968148212d184b3cd20678f0bed96/src/sdl2.f90#L452). Anyway, you can just nullify the pointer by yourself:
```fortran
image => null()
image => sdl_load_bmp('card.bmp' // c_null_char)
```
The intrinsic function `associated()` will then return `.false.` if `sdl_load_bmp()` has failed.

**Comment by freevryheid** [comment]
That works. Thanks!
