### ISSUE TITLE
SDL2_gfx support

### ISSUE THREAD

**Issue by carlkl** [interkosmos/fortran-sdl2#21]
One question: could a SDL2_gfx interface added as well? SDL2_gfx is supported by Msys2.

Or other question: in which way have the SDL2 wrappers been generated?

**Comment by interkosmos** [comment]
Have a look at [fortran-sdl2_gfx](https://github.com/freevryheid/fortran-sdl2_gfx) by @freevryheid.

The majority of the interface declarations have been written manually, except the OpenGL bindings which were mostly auto-generated by a Python script.

**Comment by carlkl** [comment]
Thank you very much for this useful information! `tst_primitives.f90` from fortran-sdl2_gfx compiles and run under Msys2!
