### ISSUE TITLE
Add the primitive to draw points/pixel

### ISSUE THREAD

**Issue by angelog0** [interkosmos/fortran-sdl2#3]
One of the basic, and most useful, primitive found in graphics libraries is that to draw points. For what I can see in `SDL2` it should be related to `SDL_RenderDrawPoint(s)`...

Thanks

**Comment by interkosmos** [comment]
The interfaces and an example `draw` have been added with commit b3910cbca4d5814027f36102ca074eca78f0e3b3.

**Comment by angelog0** [comment]
@interkosmos, thanks for this adding..

BTW, I think `sdl_quit_type` should be in upper case in the examples code (or elsewhere too?)

Thanks

**Comment by interkosmos** [comment]
Yes, you are right. Thank you for the hint.
