### ISSUE TITLE
About the SDLK constants

### ISSUE THREAD

**Issue by angelog0** [interkosmos/fortran-sdl2#6]
As I wrote elsewhere, after recent changes, this code

```
write(*,'(A,i0)') 'KEY = ', event%key%key_sym%sym
```
now works and prints the right values (ASCII code) of the key pressed

So we need the definition for SDLK_ESCAPE and friends which seem are not yet implemented. With those constants this code would work (see #4) too:

```
if (event%key%key_sym%sym == SDLK_ESCAPE) r = .true.
```

**Comment by interkosmos** [comment]
Out of curiosity: why don’t you just use `sdl_get_keyboard_state()` to handle the keyboard input?

**Comment by interkosmos** [comment]
The SDL keycodes have been added with commit 1a51d2fced9a1b9dfe09053f8752862fc2f85b6c.

**Comment by angelog0** [comment]
Thanks for the commit. 

If `event%key%key_sym%sym` works I could write a routine which return the code of key pressed and the process that code...

```
key = getevent()

select case (key)
...
```

**Comment by angelog0** [comment]
@interkosmos wrote:

>  The SDL keycodes have been added with commit 1a51d2f

Maybe we need also `SDL_BUTTON...` etc. constants?

Thanks.

**Comment by interkosmos** [comment]
`SDL_BUTTON*` parameters have been added with commit 9ebb8e40f18da3ca9694401e6026f6d8ee648b8c. Please see example `events`.
